import ExperienceList from "@/components/ExperienceList";
import experiences from "@/data/experience.json";
import projects from "@/data/projects.json";
import studyCase from "@/data/study-cases.json";
import { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Muhammad Fathurrahman",
  description: "Generated by create next app",
};

export default function Page() {
  const hasWork = experiences.some((experience) => !experience.status);

  return (
    <main className="w-full px-6 lg:py-0">
      <div className="lg:flex lg:gap-6 px mx-auto max-w-screen-xl ">
        <div className="flex-1 pt-4 md:pt-24 lg:h-screen lg:sticky lg:top-0">
          <h2 className="text-3xl sm:text-4xl font-bold leading-tight">
            Muhammad Fathurrahman
          </h2>
          <h3 className="font-semibold text-sm lg:text-base">
            Ex Developer Intern at{" "}
            <span className="hover:before:w-full relative before:absolute before:w-0 before:bottom-0 before:h-[1.2px] before:bg-red-500 before:rounded-full before:transition-all">
              Telkom Indonesia
            </span>
          </h3>
          <p className="mt-6 max-w-md text-slate-500 text-sm lg:text-base">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea quis
            architecto aperiam?
          </p>
          <p className="mt-6 max-w-md text-slate-500 text-sm lg:text-base">
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsam
            voluptates perspiciatis, nulla recusandae facilis repellendus
            dolores omnis corrupti laudantium debitis deserunt id asperiores
            quas adipisci dignissimos hic aperiam. Architecto odio maxime
            obcaecati laborum voluptatibus quia rerum eaque perspiciatis tenetur
            harum?
          </p>
        </div>

        <div className="flex-1 pt-4 md:pt-24 mt-12 lg:mt-0 selection:bg-pink-400 selection:text-white">
          <section className="transition-all hover:bg-slate-50 hover:outline-[2px] hover:outline-slate-100 px-6 py-4 rounded-xl">
            <h3 className="text-xl font-bold">Job Experience</h3>
            <ul className="mt-6">
              {hasWork && (
                <ExperienceList isActive>
                  <h4 className="text-lg font-semibold">What Next?</h4>
                  <p>Please hire me right now 😢</p>
                </ExperienceList>
              )}
              {experiences.map((experience, idx) => (
                <ExperienceList
                  key={idx}
                  isFirst={idx === 0}
                  isActive={experience.status}
                  experience={experience}
                />
              ))}
            </ul>
          </section>
          <section className="mt-4 lg:mt-12">
            <h3 className="px-6 text-xl font-bold">Projects</h3>
            <ul className="mt-6">
              {projects.map((project) => (
                <li
                  className="transition-all hover:bg-slate-50 hover:outline-[2px] px-6 py-4 hover:outline-slate-100 flex flex-col lg:flex-row items-start gap-3 mb-4 rounded-md"
                  key={project.name}
                >
                  <div className="relative aspect-video w-full lg:w-28 order-2 lg:order-1 bg-black overflow-hidden">
                    <Image
                      src={project.image}
                      fill
                      alt={project.name}
                      objectFit="fill"
                    />
                  </div>
                  <div className="flex-1">
                    <h4 className="text-lg font-semibold leading-none">
                      {project.name}
                    </h4>
                    <span>{project.project_type}</span>
                    <p className="text-slate-600 font-extralight mt-2">
                      {project.description}
                    </p>
                  </div>
                </li>
              ))}
            </ul>
          </section>
          <section className="mt-4 lg:mt-12">
            <h3 className="px-6 text-xl font-bold">Projects</h3>
            <ul className="mt-6">
              {studyCase.map((cases) => (
                <li
                  className="transition-all hover:bg-slate-50 hover:outline-[2px] px-6 py-4 hover:outline-slate-100 flex items-start gap-3 mb-4 rounded-md"
                  key={cases.name}
                >
                  <div className="flex-1">
                    <h4 className="text-lg font-semibold leading-none">
                      {cases.name}
                    </h4>
                    <p className="text-slate-600 font-extralight mt-2">
                      {cases.description}
                    </p>
                  </div>
                </li>
              ))}
            </ul>
          </section>
        </div>
      </div>
    </main>
  );
}
