import "./globals.css";
import type { Metadata } from "next";
import { Fira_Code as FiraCode } from "next/font/google";
import { cn } from "@/utils/helper";
import Navbar from "@/components/Navbar";

const inter = FiraCode({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className)}>
        <Navbar />
        <div className="mt-16">{children}</div>
      </body>
    </html>
  );
}
